### ISSUE TITLE
call :init question

### ISSUE THREAD

**Issue by amakvana** [IcarusLivesHF/Batch-Script-Projects#2]
Hi matey,

In some of your scripts, you have this as your initialisation:

```
:init 
  for /f "tokens=1 delims==" %%a in ('set') do (
	  set "unload=true"
	  for %%b in ( path ComSpec SystemRoot ) do if /i "%%a"=="%%b" set "unload=false"
	  if "!unload!"=="true" set "%%a="
  )
  set "unload="
exit /b
```

What is the purpose of this? I understand it unsets a bunch of predefined environment variables, etc. but I don't understand how not doing this affects the functionality of your scripts?

**Comment by IcarusLivesHF** [comment]
I apologize for getting to this so late.

It's not a necessity, but working in an environment with as few variables as possible helps your batch scripts perform a little more optimally. I preserve a few essential variables just in case. 

If you have any more questions let me know!

I don't usually see these, so if you would prefer, you can add me on discord: icarus00000
